### PR TITLE
Criteria lists must be a similar view in popup preview and CRUD list in goal activity feed

### LINKED ISSUE #2434: Wrong criteria color in light theme
Text is gray on white

### LINKED ISSUE #2469: Criteria lists must be a similar view in popup preview and CRUD list in goal activity feed

### PR DESCRIPTION
**Pull request by LamaEats**
This pr is includes changes about criteria, similar view for popup preview and CRUD list in goal activity section

## PR includes

- [x] Bug Fix
- [x] Refactor
- [x] Feature

## Related issues

Resolve #2469 
Resolve #2434 

## QA Instructions, Screenshots, Recordings
  
image
image
image
image

### CODE REVIEW

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx [hunk 1]
```diff
@@ -88,40 +129,202 @@ const GoalCriteria: React.FC<Omit<GoalCriteriaProps, 'id'>> = ({ title, shortId,
...
+            )}
+            {nullable(availableActions, (actions) => (
+                <TableCell width="3rem">
+                    <CriteriaActions actions={actions} />
+                </TableCell>
+            ))}
+            {nullable(mode === 'edit', () => (
+                <GoalFormPopupTrigger
+                    defaultVisible
+                    renderTrigger={({ ref }) => <div ref={ref} />}
```
Comment (asabotovich) [inline src/components/NewGoalCriteria/NewGoalCriteria.tsx:284]: empty div? 
renderTrigger --> to optional params?

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx [hunk 2]
```diff
@@ -88,40 +129,202 @@ const GoalCriteria: React.FC<Omit<GoalCriteriaProps, 'id'>> = ({ title, shortId,
...
+                    onCancel={() => setMode('read')}
+                >
+                    <GoalCriteriaSuggest
+                        id={props.goalId}
+                        defaultMode={defaultMode}
+                        values={values}
+                        // @ts-ignore
+                        onSubmit={onUpdate}
```
Comment (asabotovich) [inline src/components/NewGoalCriteria/NewGoalCriteria.tsx:292]: whats happened?

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx [hunk 3]
```diff
@@ -189,14 +392,18 @@ export const GoalCriteriaPreview: React.FC<GoalCriteriaPreviewProps> = ({ achiev
                     </Text>
                     {nullable(status === 'success', () => (
                         <CriteriaList
+                            className={classes.NewGoalCriteriaTable}
+                            goalId={goalId}
                             list={data?.map((criteria) => {
                                 if (criteria.criteriaGoal) {
                                     return {
```
Comment (asabotovich) [inline src/components/NewGoalCriteria/NewGoalCriteria.tsx:399]: is it the same?

File: src/components/GoalActivityFeed/GoalActivityFeed.tsx [hunk 4]
```diff
@@ -142,18 +145,61 @@ export const GoalActivityFeed = forwardRef<HTMLDivElement, GoalActivityFeedProps
...
-                                    onConvertToGoal={handleConvertCriteriaToGoal}
+                                    onCheck={handleUpdateCriteriaState}
+                                    onConvert={handleConvertCriteriaToGoal}
                                     onRemove={handleRemoveCriteria}
-                                    onGoalClick={onGoalClick}
-                                    validateGoalCriteriaBindings={validateGoalCriteriaBindings}
-                                    list={goal._criteria}
-                                />
+                                    list={goal._criteria?.map((criteria) => {
+                                        if (criteria.criteriaGoal) {
```
Comment (asabotovich) [inline src/components/GoalActivityFeed/GoalActivityFeed.tsx:156]: ...with this?

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx (hunk 3 above)
Comment (LamaEats) [reply src/components/NewGoalCriteria/NewGoalCriteria.tsx:399]: Yep, i don't want make component interface based on prisma typings

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx (hunk 2 above)
Comment (LamaEats) [reply src/components/NewGoalCriteria/NewGoalCriteria.tsx:292]: My bad

File: src/components/NewGoalCriteria/NewGoalCriteria.tsx (hunk 1 above)
Comment (LamaEats) [reply src/components/NewGoalCriteria/NewGoalCriteria.tsx:284]: Then form popup has not target for positioning

File: src/styles/icons.css [hunk 5]
```diff
@@ -0,0 +1 @@
+@import "@taskany/icons/style.css";
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/styles/icons.css:1]: Because TS cannot locate the css file by directly import, however a declaration typings in the icons package is correctly define

File: src/components/CriteriaForm/CriteriaForm.tsx [hunk 6]
```diff
@@ -434,6 +435,7 @@ export const CriteriaForm = ({
 
             <input type="hidden" {...register('id')} />
             <input type="hidden" {...register('selected.id')} />
+            <input type="hidden" {...register('selected._shortId')} />
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/CriteriaForm/CriteriaForm.tsx:438]: I was made common callbacks interface for any action on single criteria, which uses `UnionCriteria` as data interface. This interface has `shortId` property for open preview action directly from specific criteria

In this case added `_shortId` field needs for compatibility between some components

File: src/components/GoalFormPopupTrigger.tsx [hunk 7]
```diff
@@ -56,7 +56,7 @@ export const GoalFormPopupTrigger: FC<GoalFormPopupTriggerProps> = ({
                 interactive
                 minWidth={450}
                 maxWidth={450}
-                arrow
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/GoalFormPopupTrigger.tsx:59]: What do you mean?

[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/GoalFormPopupTrigger.tsx:59]: Oh, I get it

[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/GoalFormPopupTrigger.tsx:59]: And no, I can't 'cause [one](https://github.com/taskany-inc/bricks/blob/main/src/components/Popup/Popup.tsx#L219) and (two)[https://github.com/taskany-inc/bricks/blob/main/src/harmony/Popup/Popup.tsx#L35]

This prop in bricks lib is defined as `true`

File: src/components/CriteriaForm/CriteriaForm.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (awinogradov) [reply src/components/CriteriaForm/CriteriaForm.tsx:438]: I don't see the reason. U can fix it here or in the next issue. But in exactly next.
