### PR TITLE
Goal header redesign

### LINKED ISSUE #1045: Goal header redesign
image

image

Create statuses types and assign "completed" type to current "finished" status. Basic status types: ['not started', 'in progress', 'completed', 'failed', 'cancelled']

Count goal OKR as completed by status type

### PR DESCRIPTION
**Pull request by awinogradov**
## PR includes

- [x] Feature

## Related issues

Resolve #1045

## QA Instructions, Screenshots, Recordings
  
image

image

### CODE REVIEW

File: src/components/IssueStats/IssueStats.tsx [hunk 1]
```diff
@@ -13,38 +15,71 @@ const RelativeTime = dynamic(() => import('../RelativeTime/RelativeTime'));
...
+        <StyledIssueInfo as="span" size="m" color={gray8}>
+            {nullable(estimate, (e) => (
+                <DotSep>{formatEstimate(e, locale)}</DotSep>
+            ))}
+            {nullable(priority, (p) => (
+                <DotSep>{getPriorityText(p)}</DotSep>
+            ))}
+            {achivedCriteriaWeight !== undefined && (
+                <DotSep>
+                    <StyledDotSep>
```
Comment (awinogradov) [inline src/components/IssueStats/IssueStats.tsx:61]: Will be fixed with new bricks version

File: prisma/migrations/20230620174150_/migration.sql [hunk 2]
```diff
@@ -0,0 +1,5 @@
+-- CreateEnum
+CREATE TYPE "StateType" AS ENUM ('NotStarted', 'InProgress', 'Completed', 'Failed', 'Canceled');
+
+-- AlterTable
+ALTER TABLE "State" ADD COLUMN     "type" "StateType";
```
Comment (9teen90nine) [inline prisma/migrations/20230620174150_/migration.sql:5]: don't you want to add sql to fill the column based on current seed types?

Comment (9teen90nine) [reply prisma/migrations/20230620174150_/migration.sql:5]: it would be possible to use non-null constraint after that

**Review by 9teen90nine — APPROVED** [review]

File: prisma/migrations/20230620174150_/migration.sql (hunk 2 above)
Comment (awinogradov) [reply prisma/migrations/20230620174150_/migration.sql:5]: it's impossible to do fill them here, because you need to write smth like that:
```
if (state.title === 'Draft') ...
```

I'm not sure it's nice. We'll fill state in prod db and them add new migration with non null constraint. https://github.com/taskany-inc/issues/issues/1128
