### PR TITLE
Taskany Bot incorrect logic

### LINKED ISSUE #2143: Taskany Bot incorrect logic
- create email job for comments
- query non archived goals in statusType: InProgress, NotStarted

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Bug Fix
- [x] Feature

## Related issues

Resolve #2143

### CODE REVIEW

File: src/utils/worker/goalPingJob.ts [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+import { prisma } from '../prisma';
+import { prepareRecipients } from '../prepareRecipients';
+
+import { getSheep } from './sheep';
+import { createEmailJob } from './create';
+
+const fetchGoals = (date: Date) =>
+    prisma.goal.findMany({
+        where: {
```
Comment (awinogradov) [inline src/utils/worker/goalPingJob.ts:11]: non archived

**Review by awinogradov — CHANGES_REQUESTED** [review]

File: src/utils/worker/goalPingJob.ts [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+const commentsMinInterval = 300;
+let commentsInterval: NodeJS.Timer | null = null;
+const commentsPeriod = 1000 * 60 * 60 * 24;
+
+export const goalPingJob = async () => {
+    const { activityId } = (await getSheep()) ?? {};
+
+    if (!activityId) {
+        throw new Error('No avalible sheeps');
```
Comment (awinogradov) [inline src/utils/worker/goalPingJob.ts:43]: available

**Review by awinogradov — APPROVED** [review]

**Review by 9teen90nine — APPROVED** [review]
