### PR TITLE
fix(StarredProjects): fix empty list

### LINKED ISSUE #2827: Fix starred project list
Now on test stage was found incorrect behavior - if user haven't starred projects then list contains all projects

### PR DESCRIPTION
**Pull request by LamaEats**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #2827 

## QA Instructions, Screenshots, Recordings
  
image

### CODE REVIEW

File: trpc/router/projectV2.ts [hunk 1]
```diff
@@ -82,6 +82,10 @@ export const project = router({
         try {
             const projectIds = await getStarredProjectsIds(activityId).execute();
 
+            if (!projectIds?.length) {
+                return null;
```
Comment (9teen90nine) [inline trpc/router/projectV2.ts:86]: why not []?

Comment (LamaEats) [reply trpc/router/projectV2.ts:86]: For simplify render condition

Comment (9teen90nine) [reply trpc/router/projectV2.ts:86]: You simplify one line to mess up with nullable types :(

**Review by 9teen90nine — APPROVED** [review]

**Review by asabotovich — APPROVED** [review]
