### PR TITLE
Mention plugin for Monaco Editor

### LINKED ISSUE #2738: Mention plugin for Monaco Editor
- research Monaco Editor for plugin availability
- implement Combobox with users on `@` entered in textarea
- In fail state: find other way to add user's link to mardonw

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Feature

## Related issues

Resolve #2738 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/issues/assets/9020793/08245ea0-8fd8-4e56-8d66-c96805798a94

### CODE REVIEW

File: src/components/FormControlEditor/FormControlEditor.tsx [hunk 1]
```diff
@@ -10,16 +14,93 @@ editorLoader.config({
...
+                            endLineNumber: position.lineNumber,
+                        });
+
+                        if (line.indexOf(triggerCharacter) < 0) {
+                            return emptySuggestions;
+                        }
+
+                        const query = line.split(triggerCharacter).pop() || '';
+
+                        if (query.length <= 0) {
```
Comment (LamaEats) [inline src/components/FormControlEditor/FormControlEditor.tsx:41]: How the length can be negative?

Comment (asabotovich) [reply src/components/FormControlEditor/FormControlEditor.tsx:41]: image

File: src/components/FormControlEditor/FormControlEditor.tsx [hunk 2]
```diff
@@ -10,16 +14,93 @@ editorLoader.config({
...
+                            endColumn: position.column,
+                            startLineNumber: position.lineNumber,
+                            endLineNumber: position.lineNumber,
+                        });
+
+                        if (line.indexOf(triggerCharacter) < 0) {
+                            return emptySuggestions;
+                        }
+
+                        const query = line.split(triggerCharacter).pop() || '';
```
Comment (LamaEats) [inline src/components/FormControlEditor/FormControlEditor.tsx:39]: Maybe here to use sliced string from next  index after trigger position to line's end?

I think that transform to array is useless :)

**Review by tsumo — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]
