### PR TITLE
Bugs in criteria feature

### LINKED ISSUE #2058: Bugs in criteria feature
- Doesn't cotrect fetch the goal suggestions inside versa cirteria comppnent
- Not visible GoalCriteria in GoalActivitity component
- Not save editing critiria
- Incorrect criteria title in versa criteria

### PR DESCRIPTION
**Pull request by LamaEats**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #2058

### CODE REVIEW

**Review by asabotovich — APPROVED** [review]

File: src/components/GoalCriteria/GoalCriteria.tsx [hunk 1]
```diff
@@ -416,6 +425,37 @@ export const GoalCriteria: React.FC<GoalCriteriaProps> = ({
...
+
+        return {
+            mode: 'simple',
+            id: criteria.id,
+            title: criteria.title,
+            weight: criteria.weight > 0 ? String(criteria.weight) : '',
+        };
+    }, []);
+
+    const handleChangeInput = useCallback((val = '') => {
```
Comment (DenisVorop) [inline src/components/GoalCriteria/GoalCriteria.tsx:455]: val: string

**Review by tsumo — APPROVED** [review]

**Review by DenisVorop — APPROVED** [review]

File: src/components/GoalCriteria/GoalCriteria.tsx (hunk 1 above)
Comment (LamaEats) [reply src/components/GoalCriteria/GoalCriteria.tsx:455]: Nope, cuz it can be undefine, also TS inferred type from default variable value
