### PR TITLE
Drop unnecessary Effects

### LINKED ISSUE #1590: Drop unnecessary Effects
**Describe the bug**
Some components have unnecessary Effects that can affect performance badly:
1) [GoalParentComboBox](https://github.com/taskany-inc/issues/blob/main/src/components/GoalParentComboBox.tsx#L49)
2) GoalSuggest: [setVisible(true)](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/GoalSuggest.tsx#L70), [setVisible(false)](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/GoalSuggest.tsx#L72)
3) [InlineForm](https://github.com/taskany-inc/issues/blob/main/src/components/InlineForm.tsx#L79)
4) [ModalEvent](https://github.com/taskany-inc/issues/blob/main/src/components/ModalOnEvent.tsx#L44)
5) [State](https://github.com/taskany-inc/issues/blob/main/src/components/State.tsx#L74)
6) StateSwitch: [1](https://github.com/taskany-inc/issues/blob/main/src/components/StateSwitch.tsx#L68C13-L68C22), [2](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/StateSwitch.tsx#L74), [3](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/StateSwitch.tsx#L82)
7) [CriteriaForm](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/CriteriaForm/CriteriaForm.tsx#L219)
8) [GlobalSearch](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/GlobalSearch/GlobalSearch.tsx#L231)
9) GoalDependencyAddForm: [1](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/GoalDependencyForm/GoalDependencyForm.tsx#L75), [2](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/GoalDependencyForm/GoalDependencyForm.tsx#L90C13-L90C29)
10) [HotkeysModal](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/HotkeysModal/HotkeysModal.tsx#L56)
11) [UserSettingsPage](https://github.com/taskany-inc/issues/blob/6cf4f6a534ebc678cdd9dbe8779ffcc6b56a2d03/src/components/UserSettingsPage/UserSettingsPage.tsx#L55)
12) [useHighlightedComment](https://github.com/taskany-inc/issues/blob/main/src/hooks/useHighlightedComment.ts#L21)

**Expected behavior**
Adjust the state directly during the rendering according to the [documentation](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes).

### PR DESCRIPTION
**Pull request by DenisVorop**
## PR includes

- [x] GoalSuggest
- [x] CriteriaForm
- [x] GoalDependencyAddForm
- [x] HotkeysModal
- [x] UserSettingsPage

## Related issues
Resolve #1590

### CODE REVIEW

File: src/components/UserSettingsPage/UserSettingsPage.tsx [hunk 1]
```diff
@@ -36,32 +34,42 @@ export const UserSettingsPage = ({ user, ssrTime }: ExternalPageProps) => {
...
-    useEffect(() => {
-        setGeneralFormChanged(!shallowEqual(generalFormValues, actualUserFields));
-    }, [generalFormValues, actualUserFields]);
+    const actualValues = generalForm.watch();
+
+    const isEqual = useMemo(
+        () =>
+            actualValues.name === defaultValues.current?.name &&
+            actualValues.nickname === defaultValues.current?.nickname,
+        [defaultValues, actualValues],
```
Comment (KateKate) [inline src/components/UserSettingsPage/UserSettingsPage.tsx:56]: `defaultValues` will not change cuz it's `ref`, use [`formState.isDirty`](https://react-hook-form.com/docs/useform/formstate)  flag instead of `isEqual` and then you can remove `defaultValues = useRef` as well

File: src/components/GoalDependencyForm/GoalDependencyForm.tsx [hunk 2]
```diff
@@ -41,8 +41,9 @@ interface GoalDependencyAddFormProps {
 }
 
 export const GoalDependencyAddForm: React.FC<GoalDependencyAddFormProps> = ({ goalId, kind, isEmpty, onSubmit }) => {
-    const [selected, setSelected] = useState<GoalByIdReturnType | null>(null);
     const [query, setQuery] = useState('');
+    const selected = useRef<GoalByIdReturnType | null>(null);
```
Comment (KateKate) [inline src/components/GoalDependencyForm/GoalDependencyForm.tsx:45]: It looks tricky and it's a bad practice to pass ref as prop (<GoalSuggest ... showSuggest={!selected.current} />) because `ref` updating doesn't trigger re-render. Why do you need `selected` here? You can get selected goal id from [`getValues()`](https://react-hook-form.com/docs/useform/getvalues)

File: src/components/GoalDependencyForm/GoalDependencyForm.tsx [hunk 3]
```diff
@@ -41,8 +41,9 @@ interface GoalDependencyAddFormProps {
 }
 
 export const GoalDependencyAddForm: React.FC<GoalDependencyAddFormProps> = ({ goalId, kind, isEmpty, onSubmit }) => {
-    const [selected, setSelected] = useState<GoalByIdReturnType | null>(null);
     const [query, setQuery] = useState('');
+    const [selectedGoal, setSelectedGoal] = useState<GoalByIdReturnType | null>(null);
```
Comment (KateKate) [inline src/components/GoalDependencyForm/GoalDependencyForm.tsx:45]: Could we drop this useState and replace it with `isGoalSelected`?

```js
const values = getValues();
const isGoalSelected = !!values["relation.id"];
```

Comment (KateKate) [reply src/components/GoalDependencyForm/GoalDependencyForm.tsx:45]: But you need to add useMemo for isGoalSelected

**Review by KateKate — APPROVED** [review]
Plz consider [this comment](https://github.com/taskany-inc/issues/pull/1626#discussion_r1323231455)

File: src/components/GoalDependencyForm/GoalDependencyForm.tsx (hunk 3 above)
Comment (KateKate) [reply src/components/GoalDependencyForm/GoalDependencyForm.tsx:45]: and getValues => [watch](https://react-hook-form.com/docs/useform/watch) wo useMemo

Comment (KateKate) [reply src/components/GoalDependencyForm/GoalDependencyForm.tsx:45]:
```js
const isGoalSelected = !!watch("relation.id")
```

**Review by 9teen90nine — APPROVED** [review]

**Comment by DenisVorop** [comment]
Related https://github.com/taskany-inc/issues/issues/1705
