### PR TITLE
fix priority sorting: now sorts alphabetically

### LINKED ISSUE #1255: fix priority sorting: now sorts alphabetically

### PR DESCRIPTION
**Pull request by DenisVorop**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #1255 

## QA Instructions, Screenshots, Recordings
  
Снимок экрана 2023-07-15 в 18 09 32
Снимок экрана 2023-07-15 в 18 09 43

### CODE REVIEW

File: prisma/seed.ts [hunk 1]
```diff
@@ -301,16 +333,16 @@ seed('Default projects', async () => {
                         history: {
                             createMany: {
                                 data: [
-                                    [faker.lorem.sentence(2), goal.title, sample(allUsers).activityId, 'title'],
+                                    [faker.lorem.sentence(2), goal.title, sample(allUsers).activityId ?? '', 'title'],
```
Comment (awinogradov) [inline prisma/seed.ts:336]: ?

**Review by awinogradov — CHANGES_REQUESTED** [review]
https://github.com/taskany-inc/issues/blob/main/CONTRIBUTING.md#sending-a-pull-request

**Review by awinogradov — CHANGES_REQUESTED** [review]
PR does not match contribution guidelines.

File: prisma/seed.ts [hunk 2]
```diff
@@ -8,7 +8,30 @@ import { keyPredictor } from '../src/utils/keyPredictor';
 
 const adminEmail = process.env.ADMIN_EMAIL || 'tony@taskany.org';
 const adminPassword = process.env.ADMIN_PASSWORD || 'taskany';
-const priorities = ['Highest', 'High', 'Medium', 'Low'];
+// const priorities = ['Highest', 'High', 'Medium', 'Low'];
```
Comment (awinogradov) [inline prisma/seed.ts:11]: do not use comments to save old code, we have git for that

**Review by awinogradov — CHANGES_REQUESTED** [review]

**Review by awinogradov — APPROVED** [review]
