### PR TITLE
Fix markdown

### LINKED ISSUE #2717: Fix markdown
Return lost global typography

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #2717 

## QA Instructions, Screenshots, Recordings
  
Снимок экрана 2024-05-29 в 17 00 27

### CODE REVIEW

File: src/components/WhatsNewLayout.tsx [hunk 1]
```diff
@@ -1,13 +1,35 @@
...
 import { useTheme } from 'next-themes';
+import { Link, Image, Text } from '@taskany/bricks/harmony';
 
 interface WhatsNewLayoutProps {
     children: React.ReactNode;
 }
 
-const components = {};
+const components = {
+    a: (props: AnchorHTMLAttributes<HTMLAnchorElement>) => <Link {...props} target="_blank" view="inline" />,
```
Comment (LamaEats) [inline src/components/WhatsNewLayout.tsx:19]: Could you use single components list for both components (whatsnew/md) with in-place overrides?

**Review by LamaEats — CHANGES_REQUESTED** [review]

File: package.json [hunk 2]
```diff
@@ -49,7 +49,7 @@
     "@sentry/nextjs": "7.99.0",
     "@tanstack/react-query": "4.29.5",
     "@tanstack/react-query-devtools": "4.29.6",
-    "@taskany/bricks": "5.37.2",
+    "@taskany/bricks": "0.0.0-ef96135",
```
Comment (DenisVorop) [inline package.json:52]: be careful

**Review by LamaEats — APPROVED** [review]

**Review by tsumo — APPROVED** [review]
