### PR TITLE
Goal header is broken 

### LINKED ISSUE #1713: Goal header is broken
image

### PR DESCRIPTION
**Pull request by awinogradov**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #1713

## QA Instructions, Screenshots, Recordings

image

image

### CODE REVIEW

File: src/components/RelativeTime/RelativeTime.tsx [hunk 1]
```diff
@@ -47,13 +58,15 @@ export const RelativeTime: React.FC<RelativeTimeProps> = ({ kind, date, isRelati
     const timeValue = isRelativeTime ? dateAgo(localeDate, time, { locale }) : createLocaleDate(localeDate, { locale });
 
     return (
-        <>
-            {kind ? `${map[kind]} ` : ''}
+        <StyledRelativeTime>
+            {kind ? <span>{map[kind]}</span> : null}
```
Comment (9teen90nine) [inline src/components/RelativeTime/RelativeTime.tsx:62]: nullable?

**Review by 9teen90nine — APPROVED** [review]

**Review by asabotovich — APPROVED** [review]
