### PR TITLE
FiltersPanel is broken in ru locale

### LINKED ISSUE #1235: FiltersPanel is broken in ru locale
image

### PR DESCRIPTION
**Pull request by LamaEats**
Brand new popup-like Filters Panel
Including State, Projects, Priority, Owners, Issuers, Participants, Tags
For Projects, Owners, Issuers, Participants, Tags added search field for suggest items

## PR includes

- [x] Bug Fix
- [x] Refactor
- [x] Feature

## Related issues

Resolve #1235 

## QA Instructions, Screenshots, Recordings
  
image
image
image

### CODE REVIEW

File: src/components/FilterTabLabel.tsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+const StyledLabelWrapper = styled.div`
+    display: flex;
+    flex-direction: row;
+    flex-wrap: nowrap;
+    gap: ${gapXs};
+    width: 100%;
+`;
+
+const StyledBreakText = styled(Text)`
+    word-break: break-all;
```
Comment (awinogradov) [inline src/components/FilterTabLabel.tsx:20]: Could u create issue in bricks and move it as prop to Text component? I think it would be much better because we have a lot of places with same kind of usage. Thanks 🙏🏼

File: src/components/FilterTabLabel.tsx [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+`;
+
+export const FilterTabLabel: React.FC<TabLabelProps> = ({ text, selected }) => (
+    <StyledLabelWrapper>
+        <Text>
+            {text}
+            {`${selected?.length ? ': ' : ''}`}
```
Comment (awinogradov) [inline src/components/FilterTabLabel.tsx:27]: nullable supports array now

**Comment by LamaEats** [comment]
image

File: src/components/FilterTabLabel.tsx (hunk 1 above)
Comment (LamaEats) [reply src/components/FilterTabLabel.tsx:20]: https://github.com/taskany-inc/bricks/issues/463

File: src/components/DashboardPage/DashboardPage.tsx [hunk 3]
```diff
@@ -51,22 +51,15 @@ export const DashboardPage = ({ user, ssrTime, defaultPresetFallback }: External
...
-        setOwnerFilter,
-        setParticipantFilter,
-        setProjectFilter,
         setStarredFilter,
         setWatchingFilter,
         setSortFilter,
         setFulltextFilter,
         resetQueryState,
         setPreset,
+        batch: batchQueryState,
```
Comment (awinogradov) [inline src/components/DashboardPage/DashboardPage.tsx:62]: U can export it with `batchQueryState` name ;)

File: src/components/FilterPopup/FilterPopup.tsx [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+        display: flex;
+        flex-direction: column;
+        overflow: auto;
+        box-sizing: border-box;
+        flex: 1;
+    }
+`;
+
+const StyledPopup = styled(Popup)`
+    border-radius: ${radiusM};
```
Comment (awinogradov) [inline src/components/FilterPopup/FilterPopup.tsx:45]: Why not defaults? Popup already has border radius

File: src/components/FilterPopup/FilterPopup.tsx [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    margin-top: ${gapXs};
+    align-items: center;
+`;
+
+const StyledActionWrapper = styled.div`
+    display: flex;
+    flex-wrap: nowrap;
+    margin-left: auto;
+    gap: ${gapS};
+`;
```
Comment (awinogradov) [inline src/components/FilterPopup/FilterPopup.tsx:60]: Be consistent with empty lines ;)

File: src/components/FilterTabLabel.tsx [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+`;
+
+export const FilterTabLabel: React.FC<TabLabelProps> = ({ text, selected }) => (
+    <StyledLabelWrapper>
+        <Text color={gray9}>
+            {text}
+            {nullable(selected, () => ': ')}
+        </Text>
+        {nullable(selected, (list) => (
+            <StyledBreakText ellipsis lines={1}>
```
Comment (awinogradov) [inline src/components/FilterTabLabel.tsx:30]: Add full list to title prop

File: src/components/TagFilter.tsx [hunk 7]
```diff
@@ -1,33 +1,59 @@
...
-            items={items}
-            onChange={onChange}
-            onSearchChange={onSearchChange}
-            renderItem={({ item, selected, onClick }) => (
-                <MenuItem ghost key={item.id} selected={selected} onClick={onClick}>
-                    {item.data}
-                </MenuItem>
-            )}
-        />
+        <Tab name="tags" label={<FilterTabLabel text={text} selected={values.map(({ title }) => title)} />}>
```
Comment (awinogradov) [inline src/components/TagFilter.tsx:35]: Must be outside

**Review by awinogradov — CHANGES_REQUESTED** [review]

File: src/components/FilterPopup/FilterPopup.tsx (hunk 4 above)
Comment (LamaEats) [reply src/components/FilterPopup/FilterPopup.tsx:45]: In figma screen the popup have same a corner radius

**Comment by LamaEats** [comment]
image

File: src/components/UserFilter/UserFilter.tsx [hunk 8]
```diff
@@ -1,72 +1,111 @@
...
+    value?: string[];
+    onChange: (items: string[]) => void;
+    onSearchChange: (searchQuery: string) => void;
+    title?: {
+        inputPlaceholder: string;
+        search: string;
+    };
+}
+
+const getId = (item: User) => item.id;
```
Comment (awinogradov) [inline src/components/UserFilter/UserFilter.tsx:33]: ?

File: src/components/UserFilter/UserFilter.tsx [hunk 9]
```diff
@@ -1,72 +1,111 @@
...
-export const UserFilter: FC<{
-    users: Array<NonNullable<ActivityByIdReturnType>>;
+interface User {
+    id: string;
+    name: string | null;
+    email: string;
+    image?: string | null;
+}
+interface UserFilterProps {
+    tabName: string;
```
Comment (awinogradov) [inline src/components/UserFilter/UserFilter.tsx:21]: I'm not sure it's connected to filter. Or in general if not using filters in other places it must be tab. Like part of FiltersPanel component.

**Review by awinogradov — CHANGES_REQUESTED** [review]

File: src/components/FilterPopup/FilterPopup.tsx [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+
+const StyledTip = styled(Tip)`
+    color: ${gray10};
+    font-size: 0.75rem;
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/FilterPopup/FilterPopup.tsx:61]: Because, default `font-size` of `Tip` component little bit big for this component
I can move it behind `size` prop for `Tip` component in this PR or in the other issue

File: src/components/FilterPopup/FilterPopup.tsx [hunk 11]
```diff
@@ -0,0 +1,112 @@
...
+    padding: 0;
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/FilterPopup/FilterPopup.tsx:62]: OK, with comment above

File: src/components/FilterPopup/FilterPopup.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (awinogradov) [reply src/components/FilterPopup/FilterPopup.tsx:61]: > I can move it behind size prop for Tip component in this PR or in the other issue

Yes, plz!

[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/FilterPopup/FilterPopup.tsx:61]: https://github.com/taskany-inc/issues/issues/1694

File: src/components/FilterPopup/FilterPopup.tsx (hunk 11 above)
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/FilterPopup/FilterPopup.tsx:62]: https://github.com/taskany-inc/issues/issues/1694

File: src/components/FilterTabLabel.tsx [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+    selected?: string[];
+}
+
+const StyledLabelWrapper = styled.div`
+    display: flex;
+    flex-direction: row;
+    flex-wrap: nowrap;
+    gap: ${gapXs};
+    width: 100%;
+    // FIXME: drop after update @taskany/bricks to 4.0.2+
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/FilterTabLabel.tsx:17]: will fix by update `@taskany/bricks` in this pr

File: src/components/UserFilter/UserFilter.tsx (hunk 9 above)
Comment (LamaEats) [reply src/components/UserFilter/UserFilter.tsx:21]: this component using in three cases: owners, participants and issuers with the same behavior. Also this prop is passing into the `name` prop for `Tab` component

**Review by awinogradov — APPROVED** [review]

File: src/components/SortFilter/SortFilter.tsx [hunk 13]
```diff
@@ -28,83 +32,154 @@ const getNextDirection = (currentDirection: SortDirection): SortDirection => {
...
+                <StyledDirectionText weight="bold" size="xs" color={gray8}>
+                    {dir}
+                </StyledDirectionText>
+            ))}
+        </StyledSortItem>
     );
 };
+
+const idIsSortParam = (id: string): id is SortableProps => {
+    // Array.includes doesnt correcly works by strict sting type and strings without type casting
```
[the remark this answers is not in the document]
Comment (LamaEats) [reply src/components/SortFilter/SortFilter.tsx:93]: Yep

**Review by 9teen90nine — APPROVED** [review]
