### PR TITLE
Estimate form is not working

### LINKED ISSUE #1397: Estimate form is not working

### PR DESCRIPTION
**Pull request by DenisVorop**
## PR includes

- [x] Bug Fix
- [x] Refactor

## Related issues
Resolve #1397 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/f4c1bcf9-1bee-4455-888c-fa89cb068193

### CODE REVIEW

File: src/utils/dateTime.ts [hunk 1]
```diff
@@ -129,6 +129,17 @@ const createValue = (date: string | Date, locale: TLocale) => {
     };
 };
 
+export const incYearIfDateHasPassed = (date: Date) => {
```
Comment (awinogradov) [inline src/utils/dateTime.ts:132]: `dateTime.test.ts` ;)

**Review by awinogradov — CHANGES_REQUESTED** [review]

**Review by awinogradov — APPROVED** [review]

**Review by 9teen90nine — APPROVED** [review]
We should get rid of this picker asap
