### PR TITLE
Fix collapsable Item state

### LINKED ISSUE #1465: Fix collapsable Item state
Снимок экрана 2023-08-07 в 19 54 38

### PR DESCRIPTION
**Pull request by sab94a**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #1465 

## QA Instructions, Screenshots, Recordings
  
Снимок экрана 2023-08-07 в 19 59 32

### CODE REVIEW

File: src/components/ProjectListItemConnected.tsx [hunk 1]
```diff
@@ -54,6 +54,13 @@ export const ProjectListItemConnected: FC<{
...
     }, []);
 
+    const childrenNodeShown = childrenProjects.reduce((acum, p) => {
+        if (p._count.goals) {
+            return acum + 1;
+        }
+        return acum;
+    }, 0);
+
     // hide projects without goals
```
Comment (awinogradov) [inline src/components/ProjectListItemConnected.tsx:64]: https://github.com/taskany-inc/issues/issues/1336

**Review by awinogradov — APPROVED** [review]

**Review by 9teen90nine — APPROVED** [review]
