### PR TITLE
Sentry exception on last retry in jobs resolver

### LINKED ISSUE #1464: Sentry exception on last retry in jobs resolver

### PR DESCRIPTION
**Pull request by awinogradov**
## PR includes

- [x] Bug Fix
- [x] DX

## Related issues

Resolve #1464

### CODE REVIEW

File: src/utils/worker/index.ts [hunk 1]
```diff
@@ -20,6 +21,10 @@ console.log('Worker started successfully');
                 },
             });
 
+            if (jobs.length > 300) {
+                Sentry.captureMessage('Queue too long. Smth went wrong.');
```
Comment (9teen90nine) [inline src/utils/worker/index.ts:25]: some info about the job not queueded?

**Review by sab94a — APPROVED** [review]
