### PR TITLE
Fix submit comment form

### LINKED ISSUE #2087: Fix submit comment form
https://github.com/taskany-inc/issues/assets/95316053/3dae0bea-98cc-4fd4-9039-b0daeb94ffa2

### PR DESCRIPTION
**Pull request by DenisVorop**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #2087 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/02c4d34c-6fb9-49ad-b2c3-c302738f9690

### CODE REVIEW

File: src/components/CommentCreateForm/CommentCreateForm.tsx [hunk 1]
```diff
@@ -60,13 +60,14 @@ const CommentCreateForm: React.FC<CommentCreateFormProps> = ({
...
         ({ description }: { description: string }) => {
+            setDescription(description);
             onChange?.({ description, stateId: pushState?.id });
         },
         [onChange, pushState?.id],
     );
 
     const onCommentSubmit = useCallback(
-        async (form: CommentSchema) => {
+        (pushState?: { id: string }) => async (form: CommentSchema) => {
```
Comment (LamaEats) [inline src/components/CommentCreateForm/CommentCreateForm.tsx:70]: Wierd implementation, why is function returns function? Make the union form data argument with optional `stateId` field

**Review by LamaEats — CHANGES_REQUESTED** [review]

**Review by awinogradov — APPROVED** [review]
