### PR TITLE
one-to-many criteria to goals relation

### LINKED ISSUE #1752: Project score is incorrect
Currently we show outdated score

### LINKED ISSUE #2000: one-to-many criteria to goals relation

### PR DESCRIPTION
**Pull request by LamaEats**
Now can be link one goal to many criterias
Added a new column `criteriaGoalId` to `GoalAchieveCriteria` model
Added a new relation `goalInCriteria` between `Goal` and `GoalAchieveCriteria` model

## PR includes

- [x] Bug Fix

## Related issues

Resolve #2000
Resolve #1752

### CODE REVIEW

**Comment by LamaEats** [comment]
from https://github.com/taskany-inc/issues/pull/2001

File: src/utils/recalculateCriteriaScore.ts [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+        recalcCurrentGoalScore: () => {
+            promisesChain.push(async () => {
+                const goal = await getCurrentGoal();
+
+                if (goal) {
+                    const { goalAchiveCriteria: list, id: goalId } = goal;
+                    let score: number | null = null;
+                    if (list?.length && list.some(({ deleted }) => !deleted)) {
+                        score = calcAchievedWeight(
+                            list.map(({ weight, isDone, criteriaGoal, deleted }) => ({
```
Comment (asabotovich) [inline src/utils/recalculateCriteriaScore.ts:116]: avoid map every `calcAchievedWeight` call

**Review by asabotovich — APPROVED** [review]

**Review by tsumo — APPROVED** [review]
