### PR TITLE
Project suggestions: fix priority

### LINKED ISSUE #2826: Project suggestions: fix priority
First item should have the less length

### PR DESCRIPTION
**Pull request by asabotovich**
## PR includes

- [x] Bug Fix
- [x] Feature

## Related issues

Resolve #2826 

## QA Instructions, Screenshots, Recordings

telegram-cloud-photo-size-2-5264850239939010351-y

### CODE REVIEW

File: src/utils/filters.ts [hunk 1]
```diff
@@ -37,11 +37,7 @@ export const filtersPanelSsrInit = async ({ query, ssrHelpers, req }: SSRProps)
             query: '',
             include: queryState.issuer,
         }),
-        ssrHelpers.project.suggestions.fetch({
-            take: filtersTakeCount,
```
Comment (9teen90nine) [inline src/utils/filters.ts:41]: why did you remove limit?

Comment (asabotovich) [reply src/utils/filters.ts:41]: currently to prefetch selected filter we use `ssrHelpers.project.getByIds` endpoint (see next line)

**Review by tsumo — APPROVED** [review]

**Review by LamaEats — APPROVED** [review]
