### PR TITLE
Estimate filter doesn't work with years

### LINKED ISSUE #1593: Estimate filter doesn't work with years
https://github.com/taskany-inc/issues/assets/9020793/9923ca75-5aa6-43a7-953c-fb920aa6dcce

### PR DESCRIPTION
**Pull request by sab94a**
## PR includes

- [x] Bug Fix

## Related issues

Resolve #1593

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/issues/assets/9020793/3d659efa-2adc-4595-aba4-7230cbcea85d

### CODE REVIEW

File: trpc/queries/goals.ts [hunk 1]
```diff
@@ -35,6 +36,50 @@ const getStateFilter = (data: QueryWithFilters): Prisma.GoalFindManyArgs['where'
...
+                                    });
+                                } else {
+                                    acum.push({
+                                        y,
+                                    });
+                                }
+                            }
+
+                            return acum;
+                        }, [] as { q?: string | null; y: string }[]),
```
Comment (awinogradov) [inline trpc/queries/goals.ts:73]: You can pass it via generic `.reduce<{ q?: string | null; y: string }[]>()`

**Review by awinogradov — APPROVED** [review]

**Review by 9teen90nine — APPROVED** [review]
